### PR TITLE
run WML tools

### PR DESCRIPTION
**Pull request by cooljeanius**
So, this isn't ready to merge yet, since the campaign doesn't actually load for me yet, but I'm still opening this as a draft just so we can take a look at the kinds of changes that the various WML tools made when I ran them (you were right; they made some mistakes...)

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I'm sorry. It's impossible for me to accept a PR that has run wmlindent.

**Comment by cooljeanius** [comment]
> I'm sorry. It's impossible for me to accept a PR that has run wmlindent.

Could you expand on this? Is it just because it makes it impossible to separate the whitespace changes from the functional ones, or do you have a more general "never run `wmlindent` ever" principle?

**Comment by CelticMinstrel** [comment]
I never run wmlindent. It replaces all my tabs with spaces.

**Comment by cooljeanius** [comment]
ok I'll close this then and start afresh

**Comment by cooljeanius** [comment]
> ok I'll close this then and start afresh

version where I've started afresh is now #5

**Pull request closed without merging**
